### ISSUE TITLE
SQL injection vulnerability 

### ISSUE THREAD

**Issue by OpenGrid** [kohana/orm#120]
ORM methods are prone to SQL injection
for example method limit($number) 
should enforce / cast true natural number, not anything user passes into it. 
Same with other functions

**Comment by enov** [comment]
@OpenGrid thanks for the security report.

I am not sure if there is an actual SQL injection vulnerability, because ORM uses Kohana Database module. Both [Offset method](https://github.com/kohana/database/blob/3.3/master/classes/Kohana/Database/Query/Builder/Select.php#L312) and [limit method](https://github.com/kohana/database/blob/3.3/master/classes/Kohana/Database/Query/Builder/Where.php#L175) cast the argument to `int`.

Could you please provide us with some code that inject malicious SQL, in case you still think there is vulnerability?

PS: we are having hard time to maintain this module, as none of the active contributors are using it.

**Comment by kemo** [comment]
From where I'm standing, ORM should not be doing this / should let the Database query builder handle the typecasting if must be.

**Comment by OpenGrid** [comment]
I was able to read database tables passing "1 Procedure Analyse..." to offset function. Instead of casting to int it printed Database_Exception with data needed by the attacker

**Comment by enov** [comment]
@OpenGrid I was not able to reproduce the vulnerability.

``` php
$contact = ORM::factory('Contact')->offset('Procedure Analyse')->find(); // finds a record at offset 0
$contact = ORM::factory('Contact')->offset('1 Procedure Analyse')->find(); // finds a record at offset 1
```

There was no `Database_Exception`. It would be awesome if you detail with actual code how you could reproduce the vulnerability, so that I can take a closer look.

Thanks.

**Comment by OpenGrid** [comment]
You can mark it as closed. The issue was related to previous version of Database module which didn't have (int) cast included.

**Comment by enov** [comment]
Ah, so that settles it... Thanks @OpenGrid!  :ok_hand:
